spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ewaste_db
    username: root
    password: Shivam@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQLDialect

openweather:
  api:
    key: 35913f19ab69da02d9c8de9646346bb9
